server.port=8081

spring.application.name=patient-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mediqueue_patients}
spring.datasource.username=${DB_USER:mediqueue}
spring.datasource.password=${DB_PASSWORD:mediqueue}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
