param(
    [switch]$OpenDestination
)

$ErrorActionPreference = "Stop"
. "$PSScriptRoot\backup-common.ps1"
$cfg = Get-MediQueueBackupConfig

$backupRoot = $cfg.BackupRoot
$destinationPath = $cfg.GoogleDriveBackupPath
$stamp = Get-Date -Format "yyyyMMdd_HHmmss"
$logDir = Join-Path $backupRoot "logs"
New-Item -ItemType Directory -Force -Path $logDir | Out-Null
$logFile = Join-Path $logDir "backup-system-test-$stamp.log"

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$createdLocalPaths = New-Object System.Collections.Generic.List[string]
$createdDrivePaths = New-Object System.Collections.Generic.List[string]
$baseDir = $null

function Write-Log {
    param([string]$Message)
    $line = "$(Get-Date -Format o) $Message"
    Write-Host $line
    Add-Content -LiteralPath $logFile -Value $line -Encoding utf8
}

function Write-TestFile {
    param([string]$Path, [string]$Content)
    $dir = Split-Path -Parent $Path
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
    $createdLocalPaths.Add($Path)
}

function Invoke-External {
    param([string]$Name, [string[]]$Arguments)
    Write-Log "RUN $Name $($Arguments -join ' ')"
    & $Name @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "$Name fallo con exit code $LASTEXITCODE"
    }
}

try {
    if (-not $destinationPath) {
        throw "Configura `$GoogleDriveBackupPath en infra/backups/config/backup.local.ps1 antes de probar Google Drive Desktop."
    }

    Write-Log "CONFIG BackupRoot=$backupRoot"
    Write-Log "CONFIG GoogleDriveBackupPath=$destinationPath"
    Write-Log "CONFIG DatabaseName=$($cfg.DatabaseName) DatabaseUser=$($cfg.DatabaseUser) PostgresService=$($cfg.PostgresService)"

    Invoke-External -Name "docker" -Arguments @("version", "--format", "{{.Server.Version}}")
    Invoke-External -Name "docker" -Arguments @("compose", "exec", "-T", $cfg.PostgresService, "pg_isready", "-U", $cfg.DatabaseUser, "-d", $cfg.DatabaseName)

    $dumpFile = Join-Path $backupRoot "dumps\mediqueue_dump_backup_system_test_$stamp.dump"
    Write-TestFile -Path $dumpFile -Content "dummy dump generated by test-backup-system.ps1 at $stamp"
    $dumpHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $dumpFile).Hash
    $checksumFile = "$dumpFile.sha256"
    Write-TestFile -Path $checksumFile -Content "$dumpHash *$(Split-Path -Leaf $dumpFile)"

    $baseDir = Join-Path $backupRoot "local\mediqueue_base_backup_system_test_$stamp"
    $baseTar = Join-Path $baseDir "base.tar.gz"
    $manifest = Join-Path $baseDir "backup_manifest"
    Write-TestFile -Path $baseTar -Content "dummy base backup generated by test-backup-system.ps1 at $stamp"
    Write-TestFile -Path $manifest -Content "dummy manifest generated by test-backup-system.ps1 at $stamp"

    $walFile = Join-Path $backupRoot "wal-archive\00000001000000000000TEST_$stamp"
    Write-TestFile -Path $walFile -Content "dummy wal generated by test-backup-system.ps1 at $stamp"

    $dummyLog = Join-Path $backupRoot "logs\backup_system_dummy_$stamp.log"
    Write-TestFile -Path $dummyLog -Content "dummy log generated by test-backup-system.ps1 at $stamp"

    & "$PSScriptRoot\sync-google-drive.ps1" -DestinationPath $destinationPath
    if ($LASTEXITCODE -ne 0) { throw "sync-google-drive.ps1 fallo con exit code $LASTEXITCODE" }

    $driveDump = Join-Path $destinationPath "dumps\$(Split-Path -Leaf $dumpFile)"
    $driveChecksum = Join-Path $destinationPath "dumps\$(Split-Path -Leaf $checksumFile)"
    $driveBaseDir = Join-Path $destinationPath "local\$(Split-Path -Leaf $baseDir)"
    $driveWal = Join-Path $destinationPath "wal-archive\$(Split-Path -Leaf $walFile)"
    $driveDummyLog = Join-Path $destinationPath "logs\$(Split-Path -Leaf $dummyLog)"
    foreach ($path in @($driveDump, $driveChecksum, $driveBaseDir, $driveWal, $driveDummyLog)) {
        if (-not (Test-Path -LiteralPath $path)) {
            throw "El archivo dummy no aparecio en Google Drive local: $path"
        }
        $createdDrivePaths.Add($path)
    }

    & "$PSScriptRoot\verify-backups.ps1" -GoogleDriveBackupPath $destinationPath
    if ($LASTEXITCODE -ne 0) { throw "verify-backups.ps1 fallo con exit code $LASTEXITCODE" }

    Write-Log "CHECKLIST Docker=OK PostgreSQL=OK DummySync=OK VerifyBackups=OK"
    Write-Log "TEST_BACKUP_SYSTEM_OK"

    if ($OpenDestination) {
        Start-Process explorer.exe -ArgumentList $destinationPath
    }
} catch {
    Write-Log "ERROR $($_.Exception.Message)"
    if ($OpenDestination -and $destinationPath -and (Test-Path -LiteralPath $destinationPath)) {
        Start-Process explorer.exe -ArgumentList $destinationPath
    }
    exit 1
} finally {
    foreach ($path in $createdLocalPaths) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Force -ErrorAction SilentlyContinue
        }
    }
    if ($baseDir -and (Test-Path -LiteralPath $baseDir)) {
        Remove-Item -LiteralPath $baseDir -Recurse -Force -ErrorAction SilentlyContinue
    }
    foreach ($path in $createdDrivePaths) {
        if (Test-Path -LiteralPath $path) {
            Remove-Item -LiteralPath $path -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

exit 0
