scope: mediqueue-postgres-ha
namespace: /service/
name: patroni-postgres-2

restapi:
  listen: 0.0.0.0:8008
  connect_address: patroni-postgres-2:8008

etcd3:
  hosts: etcd-1:2379,etcd-2:2379,etcd-3:2379

bootstrap:
  dcs:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_connections: 300
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 256MB
        archive_mode: "on"
        archive_timeout: 300
        archive_command: "mkdir -p /var/lib/postgresql/wal-archive/patroni && (test -f /var/lib/postgresql/wal-archive/patroni/%f || cp %p /var/lib/postgresql/wal-archive/patroni/%f)"
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5
  users:
    mediqueue:
      password: mediqueue
      options:
        - createdb
  post_init: bash /etc/patroni/initdb/create-mediqueue-db.sh

postgresql:
  listen: 0.0.0.0:5432
  connect_address: patroni-postgres-2:5432
  data_dir: /home/postgres/pgdata/pgroot/data
  bin_dir: /usr/lib/postgresql/16/bin
  authentication:
    superuser:
      username: postgres
      password: postgres
    replication:
      username: replicator
      password: replicator
  parameters:
    unix_socket_directories: /var/run/postgresql

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
