version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-schedule-db
    environment:
      POSTGRES_DB: mediqueue_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mediqueue-network

  mediqueue-schedule-service:
    container_name: mediqueue-schedule-service
    build: .
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mediqueue_schedule
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8082:8082"
    networks:
      - mediqueue-network

volumes:
  postgres_data:

networks:
  mediqueue-network:
    driver: bridge
