spring.application.name=mediqueue-schedule-service

server.port=8082

spring.datasource.url=${SCHEDULE_DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info
