global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers: []

rule_files: []

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: api-gateway-lb
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway-lb:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - api-gateway
        type: A
        port: 8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: patient-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - patient-service:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: schedule-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - schedule-service:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: appointment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - appointment-service:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: payment-lb
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - payment-lb:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    dns_sd_configs:
      - names:
          - payment-service
        type: A
        port: 8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - notification-service:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq:15692
    metrics_path: /metrics
